# -*- coding: utf-8 -*-
"""Projeto de Análise da Covid-19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15j-Afivmp7yUHWwcgWYsXr3_QxUpEsbr
"""

import pandas as pd

corona = pd.read_csv('covid19_italy_region.csv')

corona

corona.head()

corona['RegionName'].value_counts().head(50)

#50 casos de mo
corona['Deaths'].values_counts().head(50)

