# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f04crceABqgMU36VLr4vQXnFYn02v_ll
"""

import pandas as pd
import numpy as np
import seaborn as sns

from google.colab import drive
drive.mount('/content/gdrive')

dados = pd.read_csv('spotify.csv')

dados.head()

dados.info()

dados['Price'].head(10)

dados['Title'].head(10)

deezer = pd.read_csv('deezer.csv')

deezer.head()

deezer.info()

planos_de_celular = pd.read_csv('planos_de_celular.csv')

planos_de_celular.head(20)

